### PR TITLE
Added Scroll Button in header.ejs

### PR DESCRIPTION
**Pull request by SattyamSamania**
I have created Scroll Button in header.ejs file and added a gif in the Gif folder.

### CODE REVIEW

**Comment by Kritika30032002** [comment]
send the ss of the preview!

**Comment by SattyamSamania** [comment]
> @SattyamSamania send the ss of the preview!

Sure. This is the Screenshot with the code I have written:
image

**Comment by Kritika30032002** [comment]
Can u make it as a button or it should match the color theme of the project.

**Comment by SattyamSamania** [comment]
> Can u make it as a button or it should match the color theme of the project.

Sure

**Comment by Kritika30032002** [comment]
> > Can u make it as a button or it should match the color theme of the project.
> 
> I will share you ss then you decide if the button is looking better or not.

okay

**Comment by SattyamSamania** [comment]
> > > Can u make it as a button or it should match the color theme of the project.
> > 
> > 
> > I will share you ss then you decide if the button is looking better or not.
> 
> okay

Screenshot (262)

**Comment by SattyamSamania** [comment]
> > > Can u make it as a button or it should match the color theme of the project.
> > 
> > 
> > I will share you ss then you decide if the button is looking better or not.
> 
> okay

I have checked by adding random text and it's working fine. Should I make a PR now?

**Comment by Kritika30032002** [comment]
> Can u make it as a button or it should match the color theme of the project.

@SattyamSamania done these changes?

**Comment by SattyamSamania** [comment]
> > Can u make it as a button or it should match the color theme of the project.
> 
> @SattyamSamania done these changes?

you can check ss. I Have made a button similar to the background of navbar.

**Comment by Kritika30032002** [comment]
image

**Comment by SattyamSamania** [comment]
> > > > Can u make it as a button or it should match the color theme of the project.
> > > 
> > > 
> > > @SattyamSamania done these changes?
> > 
> > 
> > you can check ss. I Have made a button similar to the background of navbar.
> 
> use this image instead http://cdn.onlinewebfonts.com/svg/img_71311.png

Okay

**Comment by Kritika30032002** [comment]
is it done @SattyamSamania

**Pull request merged**
