### PR TITLE
Corrected Button UI

### PR DESCRIPTION
**Pull request by singhcoder694**
#72 
Created own Buttons which are perfect for all screen sizes and applied it to all the required positions on website.

### CODE REVIEW

**Comment by Kritika30032002** [comment]
resolve the conflicts

also tell your program name?

**Comment by singhcoder694** [comment]
@Kritika30032002 Merging is blocked, but why? I have changed the style of button for better UI experience on every screen size by removing Bootstrap classes and makin my own button across all websites... Can you help me with this...

**Comment by Kritika30032002** [comment]
Share the screenshots 
also I will merge Don't worry for that

**Comment by singhcoder694** [comment]
Ok here are the screen shots....
Screenshot 2023-12-08 173253
Screenshot 2023-12-08 173309
Screenshot 2023-12-08 173318

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Comment by singhcoder694** [comment]
> Thanks for your Valuable contribution. Don't forget to star the repo.

Already Starred😊

**Pull request merged**
