### PR TITLE
Contact page added

### PR DESCRIPTION
**Pull request by singhcoder694**
#83 Add a Contact Us page

**RESPONSIVE**
Screenshot 2023-12-12 144912
Screenshot 2023-12-12 145031
Screenshot 2023-12-12 145608
Screenshot 2023-12-12 145642

Functionalities:
1.) Can send direct email by clicking send to any email just specify in contat.ejx code.
2.) Success and Error message pop up.
3.) Dynamic Address is Added using google map ifram.

### CODE REVIEW

**Comment by singhcoder694** [comment]
@Kritika30032002 resolved rises automatically when you merge any other pr having changes in same file as of mine.... How and why does this occur... Because when I created PR it didn't have any conflict....

**Comment by Kritika30032002** [comment]
when changes conflicts then merge conflicts occurs.

**Comment by Kritika30032002** [comment]
Remove contact number and  location and email

**Comment by Kritika30032002** [comment]
also this page is lookig very different from entire website so modify its ui

**Pull request closed without merging**
