### PR TITLE
Merge pull request #53 from gauravtomar7/branch

### PR DESCRIPTION
**Pull request by gauravtomar7**
secrtesd
Home_Page
1. Added Background colors in all pages to look more user-friendly
2) Changed the UI of About page

Hope this improves The_Secrets

### CODE REVIEW

**Comment by gauravtomar7** [comment]
@Kritika30032002 why I'm getting this error Merging is blocked.
If you can resolve this from your side it would be great.
ohhhh

**Comment by Kritika30032002** [comment]
the image that was on about page, don't remove it, adjust it according to ui

**Comment by Kritika30032002** [comment]
else ui is looking good. great!

**Comment by gauravtomar7** [comment]
Added the image in the about page 
okkk

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to star the repo.

**Pull request merged**
