### PR TITLE
Fix: comment all console log fixes:- #57

### PR DESCRIPTION
**Pull request by ashmit-coder**
Fixes: #57

### CODE REVIEW

**Comment by Kritika30032002** [comment]
Are all the console from all files are commented?

Also mention program name?

**Comment by ashmit-coder** [comment]
1. Yes commented all console.log from alll files.
2. KWOC , looking forward to contribute in harder issues.

**Comment by Kritika30032002** [comment]
I can see the changes has been done in 1 file only. Does any other fie do not contain logs?

**Comment by Kritika30032002** [comment]
Also it is not assigned to you so this pr cannot be merged

**Pull request closed without merging**
