### PR TITLE
Fix the Button UI

### PR DESCRIPTION
**Pull request by WolfSlayer2**
#### Done with making the buttons more clean & responsive like fixing their column size, aligning them & giving a gap between them.

### CODE REVIEW

**Comment by WolfSlayer2** [comment]
idk why i am getting merging blocked issue can you try to fix it from your side ?

**Comment by Kritika30032002** [comment]
show screenshot

**Comment by WolfSlayer2** [comment]
Screenshot

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to star the repo.

**Pull request merged**
