### PR TITLE
Made whole website responsive

### PR DESCRIPTION
**Pull request by singhcoder694**
**Solved issue: #82 , Issue Name: Make website Responsive, Program Name : CodePeak'23.**

Earlier website look on mobile screens Screenshots....
Screenshot 2023-12-09 102737
Screenshot 2023-12-09 102802

<br></br>
But now it looks like this.....
<br></br>
Screenshot 2023-12-09 120035
Screenshot 2023-12-09 120047
Screenshot 2023-12-09 120107

Responsive on all size of screens.....

I also make Go to Top button look better....

### CODE REVIEW

**Comment by Kritika30032002** [comment]
1. Firstly it has merge conflicts.
2. Navbar responsiveness is not right. Have look to other website and understand.
[Hint:LOGO of website]

**Comment by singhcoder694** [comment]
Changed the UI for navbar .... And as well Go to Top button for better UX...
Screenshot 2023-12-09 210030
Screenshot 2023-12-09 210039
Screenshot 2023-12-09 210049

**Comment by Kritika30032002** [comment]
home and about should take full width not half

also resolve the conflicts

**Comment by singhcoder694** [comment]
Done....
Screenshot 2023-12-10 155850

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Comment by singhcoder694** [comment]
@Kritika30032002 I have also updated the Register button as well as improved UI for GoToTop button, if you can count them as Bonus Points as per CodePeak'23.

**Comment by Kritika30032002** [comment]
i am not able to see any major change in gototop button.

**Pull request merged**
