### PR TITLE
added animation to homepage

### PR DESCRIPTION
**Pull request by aindree-2005**
Added animation to homepage

### CODE REVIEW

**Comment by Kritika30032002** [comment]
program name?

**Comment by Kritika30032002** [comment]
also share screenshot or video to show change

**Comment by aindree-2005** [comment]
Screenshot (235)
Not sure how to screen record. So I added a still of the animation

https://app.lottiefiles.com/animation/9736906e-55e4-48b8-9e60-7f536bea9aa2
Here's the lottie file

**Comment by Kritika30032002** [comment]
unable to view it 
you can upload video directly here by drag and drop

**Comment by aindree-2005** [comment]
https://github.com/Kritika30032002/Top_Secrets/assets/68018372/2e24c43d-23e6-4176-be14-9678de357816
@Kritika30032002 I don't have a screen recorder in my laptop. So I am uploading a video  I took with my phone

**Comment by Kritika30032002** [comment]
Animation is not related to website and is not suited to it also. Try something relatable to website

**Pull request closed without merging**
