### PR TITLE
Modified Contact Page

### PR DESCRIPTION
**Pull request by singhcoder694**
Screenshot 2023-12-14 090305
Screenshot 2023-12-14 090321
Screenshot 2023-12-14 090351
Screenshot 2023-12-14 090414

- Added all functionalities.
- Matches with website.
- Responsive.
- Dynamic Map.
- Dynamic Mailing.

### CODE REVIEW

**Comment by Kritika30032002** [comment]
I told you to remove map also

and then center align the other elements

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
share the screenshot to get approved

**Comment by singhcoder694** [comment]
Screenshot 2023-12-14 100756
Screenshot 2023-12-14 100839

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Pull request merged**
