### PR TITLE
register-alert-toast-notifications

### PR DESCRIPTION
**Pull request by surya-nand**
1. On register click modified the post response to send status of register click event
2. Added a script in register.ejs to handle the response
3. Added toast script to change alert notifications from default windows alert to toastify toast notifications
4. Toastify references: https://github.com/apvarun/toastify-js/blob/master/README.md

### CODE REVIEW

**Comment by surya-nand** [comment]
Screenshot (413)
Screenshot (412)
Screenshot (411)

**Comment by Kritika30032002** [comment]
I think color of notification should be changed as it doesn't match with the project

**Comment by Kritika30032002** [comment]
and ensure that proper conditions have been applied of displaying these notifications

**Comment by surya-nand** [comment]
Screenshot (418)
1. Register-toasts-notification-handled
2. MONGODB server is shifted to env file and made changes to catch error during database connection

**Comment by Kritika30032002** [comment]
why your pages Background color is different?
You have to just add notification part

**Comment by surya-nand** [comment]
Screenshot (421)
Screenshot (422)
 
Background-color-change-restored after syncing the fork with latest commits.

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Pull request merged**
