### PR TITLE
Password Crediablilty

### PR DESCRIPTION
**Pull request by codesmith25103**
Now user must enter 8 character password
Password must contain 1 uppercase character, 1 lowercase character, 1 number and 1 special character
Register page will show error if following rules are not applied
image
image
image

### CODE REVIEW

**Comment by Kritika30032002** [comment]
When user clicks on the input box then these rules must be shown , should not be added in ui

**Comment by codesmith25103** [comment]
Rules are not added in UI. When user will click register button, and if password does not match criteria than error will shown. If user has followed all the rule except "atleast one digit rule" then only that error will be shown.

**Comment by Kritika30032002** [comment]
shown me the actual working through video

**Comment by codesmith25103** [comment]
This is required video. It is showing functionality of the site

https://user-images.githubusercontent.com/102778847/207972721-c0a18e60-4099-4d0a-92f0-b03298ac2036.mp4

**Comment by Kritika30032002** [comment]
You can share the video of changes so that I can merge it. @codesmith25103

**Pull request closed without merging**
