### PR TITLE
Fixed the login page layout and button ui

### LINKED ISSUE #80: Login Page UI Issue
image

UI should be same as of register page

### PR DESCRIPTION
**Pull request by Afterdie**
closes #80

### CODE REVIEW

**Comment by Kritika30032002** [comment]
screenshot?

**Comment by Kritika30032002** [comment]
also check its responsiveness

**Comment by Afterdie** [comment]
image
image

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Pull request merged**
