### PR TITLE
Code Modularized: Separate Backend and Frontend Initialization (#47)

### LINKED ISSUE #47: initialising backend and frontend saperately
will help new user to contribute easily

### PR DESCRIPTION
**Pull request by stupiddint**
* fix issue #47

### CODE REVIEW

**Comment by stupiddint** [comment]
close this pr please.

**Comment by Kritika30032002** [comment]
take the updated pull and checked everything should be working fine.

**Comment by stupiddint** [comment]
i have moved all the previous files to a backend folder, then Updated and modularized the code in for improved organization and maintainability.

**Comment by stupiddint** [comment]
The code is working well and producing the same output as before.
running backend in vscode

viewing home page in the browser

**Comment by stupiddint** [comment]
after merging this pr, next we can work on
- updating readme file
- converting ejs to html file

**Comment by stupiddint** [comment]
Currently, we are using HTML, CSS, and JavaScript (initialized with Vite) for the frontend and Node.js with MongoDB for the backend

**Comment by stupiddint** [comment]
@Kritika30032002 why didn't you merge this pr, 
Is there any changes needed?

**Pull request closed without merging**
