### PR TITLE
Added Scroll to Top Button

### PR DESCRIPTION
**Pull request by SattyamSamania**
I have Created Scroll to Top Button using HTML, CSS and JS in the secrets.ejs file.

### CODE REVIEW

**Comment by SattyamSamania** [comment]
Hey @Kritika30032002 I think it requires review from the Maintainer before merging.

**Comment by Kritika30032002** [comment]
Send the video to show its working

Also I will be merging

**Comment by Kritika30032002** [comment]
@SattyamSamania R U working?

**Comment by SattyamSamania** [comment]
> @SattyamSamania R U working?

I will send video today. Any changes in code required?

**Comment by Kritika30032002** [comment]
> > @SattyamSamania R U working?
> 
> I will send video today. Any changes in code required?

How can I tell the changes without seeing the video?

**Comment by SattyamSamania** [comment]
> > > @SattyamSamania R U working?
> > 
> > 
> > I will send video today. Any changes in code required?
> 
> How can I tell the changes without seeing the video?

Hey @Kritika30032002 I am getting this kind of error. can you give me suggestion what to do next?

Screenshot (271)

**Comment by Kritika30032002** [comment]
using mac or windows?

**Comment by SattyamSamania** [comment]
> using mac or windows?

Windows

**Comment by Kritika30032002** [comment]
mongoose installation is not done properly

**Comment by SattyamSamania** [comment]
> mongoose installation is not done properly

@Kritika30032002 I have installed Mongodb Compass

**Comment by Kritika30032002** [comment]
install mongoose also

**Comment by SattyamSamania** [comment]
> install mongoose also
Installed. Still it's showing like that only.

**Comment by SattyamSamania** [comment]
> install mongoose also

It's opening but I am not able to register or login.

**Comment by Kritika30032002** [comment]
> > install mongoose also
> 
> It's opening but I am not able to register or login.

Join the discord channel and have the conversation there.

**Pull request closed without merging**
