### PR TITLE
Scroll to top button added in the footer.ejs file.

### PR DESCRIPTION
**Pull request by dikshapadi**

### CODE REVIEW

**Comment by Kritika30032002** [comment]
send the video showing its working

**Comment by dikshapadi** [comment]
Yes sure , in a bit 


> send the video showing its working

**Comment by dikshapadi** [comment]
> screen-capture.webm

**Comment by dikshapadi** [comment]
> send the video showing its working

[screen-capture (1).webm](https://user-images.githubusercontent.com/95542633/206264107-d8d2d44a-0792-48cd-a56a-b848505dde40.webm)

**Comment by Kritika30032002** [comment]
add it to the secrets page not to the home page

**Comment by dikshapadi** [comment]
But there doesnt seem to be a secrets page yet , so i added it to the footer so that it appears on every webpage that opens up(including the register and login page)

**Comment by Kritika30032002** [comment]
After login and register , secrets page can be accessed and only on secrets page it is required, not on any other page

**Comment by dikshapadi** [comment]
[screen-capture (2).webm](https://user-images.githubusercontent.com/95542633/206267565-0ec8a3d9-cbfe-4255-99a4-28704a331cdf.webm)

**Comment by Kritika30032002** [comment]
will check and do the changes if required and let you know by tomorrow

**Comment by dikshapadi** [comment]
Okay Kritika , thank you !

**Comment by Kritika30032002** [comment]
@dikshapadi you can start working now!

**Comment by Kritika30032002** [comment]
@dikshapadi Are u working on this?

**Pull request closed without merging**
