### PR TITLE
added footer (Fixes issue 2)

### PR DESCRIPTION
**Pull request by iamatifmoin**
- I have added a footer which matches the color scheme of the website.
- I have added the tagline.
- I have also added the social media links.

This is what it looks like:
foot

This PR fixes issue #2

### CODE REVIEW

**Comment by Kritika30032002** [comment]
remove leetcode and codechef socials 

use image and anchor tag to link instead of text. and add copyright line and remove follow line.

Add "Made by Kritika Gupta" and name must be linked with by github or linkedin account.

**Comment by Kritika30032002** [comment]
Great!

**Comment by iamatifmoin** [comment]
This counts towards my contribution in KWoC right? @Kritika30032002

**Comment by Kritika30032002** [comment]
Not sure! Let's wait for the reply of admins in the KWOC discord channel to your query.

**Comment by Kritika30032002** [comment]
@iamatifmoin  If not then I will undo the changes and you can again send me the same pr or can contribute to more issues

**Comment by iamatifmoin** [comment]
@Kritika30032002 
Okay thankyou!

**Comment by Kritika30032002** [comment]
Welcome! 
You can now solve another issue or create a new issue and work on it.

**Pull request merged**
