### PR TITLE
Enhancement the UI of Login & Register page

### PR DESCRIPTION
**Pull request by SomilRathore01**
I have enhanced the UI of login page which was issue no. #10 
Also introduced some animations on the page.
Screenshot (333)
Screenshot (334)
Screenshot (335)
Screenshot (336)
Screenshot (337)
Screenshot (338)
Screenshot (339)
Screenshot (340)

### CODE REVIEW

**Comment by Kritika30032002** [comment]
Its not looking good.

**Comment by SomilRathore01** [comment]
@Kritika30032002 Should I change background or to apply some more styles.

**Comment by Kritika30032002** [comment]
> @Kritika30032002 Should I change background or to apply some more styles.

okay

**Comment by SomilRathore01** [comment]
Please firstly run my code to see those animations and all transitions.
Now I have made slight changes in background and else.
Screenshot (343)

**Pull request closed without merging**
